Upgrade to ruby 2.1.7
Fixes the following error I encountered while running docker build:

```
ERROR: unsatisfiable constraints:
  ruby-dev-2.1.7-r0:
      breaks: world[ruby-dev=2.1.5-r1]
```